services:
  - type: web
    name: droitgpt-indexer
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node indexer.js
    rootDir: indexer
    autoDeploy: true
    branch: main
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false

  - type: web
    name: droitgpt-pdf-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: pdf-service
    autoDeploy: true
    branch: main
    envVars:
      - key: OPENAI_API_KEY
        sync: false
