// bp/core/grantsSources.js

export const GRANT_TYPES = [
  "grant",
  "scholarship",
  "call_for_projects",
  "tender",
  "competition",
  "accelerator",
  "fellowship",
  "ngo_funding",
  "other",
];

export const GRANT_STATUSES = ["open", "expired", "unknown", "draft_review", "hidden"];

export const DEFAULT_GRANT_SOURCES = [
  {
    name: "Funds for NGOs",
    baseUrl: "https://www2.fundsforngos.org",
    url: "https://www2.fundsforngos.org/category/latest-funds-for-ngos/",
    category: "ngo_funding",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Opportunities for Africans",
    baseUrl: "https://www.opportunitiesforafricans.com",
    url: "https://www.opportunitiesforafricans.com/",
    category: "fellowship",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "YouthOp",
    baseUrl: "https://www.youthop.com",
    url: "https://www.youthop.com/",
    category: "scholarship",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Opportunity Desk",
    baseUrl: "https://opportunitydesk.org",
    url: "https://opportunitydesk.org/",
    category: "fellowship",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Grants.gov",
    baseUrl: "https://www.grants.gov",
    url: "https://www.grants.gov/search-grants",
    category: "grant",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "UNDP Funding",
    baseUrl: "https://www.undp.org",
    url: "https://www.undp.org/procurement",
    category: "tender",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "UNICEF",
    baseUrl: "https://www.unicef.org",
    url: "https://www.unicef.org/supply/procurement-services",
    category: "tender",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "USAID",
    baseUrl: "https://www.usaid.gov",
    url: "https://www.usaid.gov/work-usaid/find-a-funding-opportunity",
    category: "grant",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "European Commission International Partnerships",
    baseUrl: "https://international-partnerships.ec.europa.eu",
    url: "https://international-partnerships.ec.europa.eu/funding-and-technical-assistance_en",
    category: "call_for_projects",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Mastercard Foundation",
    baseUrl: "https://mastercardfdn.org",
    url: "https://mastercardfdn.org/",
    category: "scholarship",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "African Development Bank",
    baseUrl: "https://www.afdb.org",
    url: "https://www.afdb.org/en/projects-and-operations/procurement",
    category: "tender",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "World Bank",
    baseUrl: "https://www.worldbank.org",
    url: "https://projects.worldbank.org/en/projects-operations/procurement",
    category: "tender",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "UNGM Procurement Notices",
    baseUrl: "https://www.ungm.org",
    url: "https://www.ungm.org/Public/Notice",
    category: "tender",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Segal Family Foundation",
    baseUrl: "https://www.segalfamilyfoundation.org",
    url: "https://www.segalfamilyfoundation.org/for-partners/",
    category: "ngo_funding",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "Global Innovation Fund",
    baseUrl: "https://www.globalinnovation.fund",
    url: "https://www.globalinnovation.fund/apply/about-our-grants/",
    category: "grant",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Echoing Green",
    baseUrl: "https://echoinggreen.org",
    url: "https://echoinggreen.org/fellowship/",
    category: "fellowship",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Halcyon",
    baseUrl: "https://www.halcyonhouse.org",
    url: "https://www.halcyonhouse.org/fellowship",
    category: "accelerator",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Ygap",
    baseUrl: "https://ygap.org",
    url: "https://ygap.org/",
    category: "accelerator",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
  {
    name: "Anza Entrepreneurs",
    baseUrl: "https://anzaentrepreneurs.co",
    url: "https://anzaentrepreneurs.co/",
    category: "accelerator",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "Tony Elumelu Foundation",
    baseUrl: "https://www.tonyelumelufoundation.org",
    url: "https://www.tonyelumelufoundation.org/",
    category: "accelerator",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "Africa's Business Heroes",
    baseUrl: "https://africabusinessheroes.org",
    url: "https://africabusinessheroes.org/en/",
    category: "competition",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "Orange Social Venture Prize",
    baseUrl: "https://entreprend.orange.com",
    url: "https://entreprend.orange.com/en/orange-social-venture-prize/",
    category: "competition",
    preferredLanguage: "en",
    region: "Africa",
    active: true,
  },
  {
    name: "GSMA Innovation Fund",
    baseUrl: "https://www.gsma.com",
    url: "https://www.gsma.com/solutions-and-impact/connectivity-for-good/mobile-for-development/gsma-innovation-fund/",
    category: "grant",
    preferredLanguage: "en",
    region: "global",
    active: true,
  },
];

export function normalizeGrantType(value) {
  const s = String(value || "").trim().toLowerCase();
  const aliases = {
    call: "call_for_projects",
    "call-for-projects": "call_for_projects",
    appel: "call_for_projects",
    "appel-a-projets": "call_for_projects",
    "appel-d-offres": "tender",
    "appel-offres": "tender",
    tender: "tender",
    tenders: "tender",
    procurement: "tender",
    bid: "tender",
    bids: "tender",
    rfp: "tender",
    rfq: "tender",
    market: "tender",
    marche: "tender",
    "marché": "tender",
    bourse: "scholarship",
    fellowship: "fellowship",
    accelerator: "accelerator",
    accelerateur: "accelerator",
    incubator: "accelerator",
    competition: "competition",
    concours: "competition",
    ngo: "ngo_funding",
    ong: "ngo_funding",
    subvention: "grant",
  };
  const normalized = aliases[s] || s;
  return GRANT_TYPES.includes(normalized) ? normalized : "other";
}

export function normalizeGrantStatus(value) {
  const s = String(value || "").trim().toLowerCase();
  return GRANT_STATUSES.includes(s) ? s : "draft_review";
}
